server:
  port: 8082

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/safeguard?autoReconnect=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#      properties:
#        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true

#spring:
#  datasource:
#    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
#    username: postgres.ffbhvzjziktornstlruj
#    password: g1udvbL3pMwLUOY4
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 3   # keep <= Supabase pool_size
#      minimum-idle: 1
#      idle-timeout: 300000
#      max-lifetime: 1800000
#      connection-timeout: 30000

#  spring:
#    datasource:
#properties:
#  statement_timeout: 60000



spring:
  datasource:
    url: jdbc:postgresql://ep-curly-recipe-a1t8zhfh-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_abjYkXT5g1GE
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: maheshkulkarni9797@gmail.com
    password: wofqmvqxwylqikle
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 20000
          timeout: 20000
          writetimeout: 20000

  web:
    cors:
      allowed-origins: "http://127.0.0.1:5500"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  pattern:
    file: "%d{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:/Users/shree/Desktop/application.log

jwt:
   secret: MVyS5KziwA8qlpF7r2Cq3vZK5eUo8n1X1W7_TBlJtRc
   expiration: 86400000
